[versions]
agp = "8.3.2"
kotlin = "1.9.0"
core = "1.13.1"

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

